# Generated by Django 3.1.7 on 2021-03-26 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('zirbana', models.IntegerField(verbose_name='مساحت زیر بنا متر مربع')),
                ('tedad_tabaqat', models.IntegerField(verbose_name='تعداد طبقات پروژه')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='آددرس پروژه')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='توضیحات پروژه')),
                ('project_status', models.CharField(choices=[('a', 'در حال انجام'), ('b', 'پایان یافته')], max_length=1, verbose_name='وضعیت پروژه')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد پروژه')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='مدیر پروژه')),
                ('Members', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='انتخاب شرکا')),
            ],
            options={
                'verbose_name': 'پروژه عمرانی',
                'verbose_name_plural': 'پروژه های عمرانی',
            },
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('amount', models.BigIntegerField(verbose_name='مقدار هزینه')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('pay_mehod', models.CharField(choices=[('n', 'نقد'), ('c', 'چک')], max_length=1, verbose_name='شیوه پرداخت')),
                ('category_pay', models.CharField(choices=[('a', 'تامین مالی از مالک'), ('b', 'فروش آهن آلات'), ('c', 'فروش ملک'), ('d', 'سایر')], max_length=1, verbose_name='از کدام منبع درآمد داشتید')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karfarmaonline.project', verbose_name='پروژه مربوطه')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='هزینه شده توسط ')),
            ],
            options={
                'verbose_name': 'درآمد',
                'verbose_name_plural': 'درآمد ها',
            },
        ),
        migrations.CreateModel(
            name='expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('amount', models.BigIntegerField(verbose_name='مقدار هزینه کرد به تومان')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('pay_mehod', models.CharField(choices=[('n', 'نقد'), ('c', 'چک')], max_length=1, verbose_name='شیوه پرداخت')),
                ('category_pay', models.CharField(choices=[('a', 'صدور پروانه'), ('b', 'شهرداری'), ('c', 'آرماتور بند'), ('d', 'شرکت بتن'), ('e', 'آهن آلات'), ('f', 'تاسیسات'), ('g', 'مصالح'), ('i', 'دستمزد کارگر بنا'), ('j', 'تخریب'), ('k', 'آب و برق و گاز'), ('l', 'کرایه تجهیزات'), ('m', 'متفرقه')], max_length=1, verbose_name='در کدام شاخه هزینه کردید')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karfarmaonline.project', verbose_name='پروژه مربوطه')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='هزینه شده توسط ')),
            ],
            options={
                'verbose_name': 'هزینه کرد',
                'verbose_name_plural': ' هزینه کرد ها',
            },
        ),
    ]
