# Generated by Django 3.1.7 on 2021-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarmaonline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ ایجاد پروژه'),
        ),
    ]
