version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - alfax_static_volume:/alfax/static
      - alfax_media_volume:/alfax/media
    networks:
      - nginx_network

volumes:
  alfax_static_volume:
    external: true
  alfax_media_volume:
    external: true
networks: 
  nginx_network:
    external: true