# Generated by Django 3.1.7 on 2021-03-24 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی پروژه',
                'verbose_name_plural': 'دسته بندی پروژه  بر اساس مهارت',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Projects_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('project_customer', models.CharField(default=None, max_length=200, verbose_name='سفارش دهنده یا مشتری پروژه')),
                ('project_subject', models.CharField(max_length=200, verbose_name='موضوع پروژه یا توضیح کوتاه')),
                ('project_slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ پروژه')),
                ('project_description', models.TextField(default=None, verbose_name='توضیحات')),
                ('project_thumbnail', models.ImageField(upload_to='project_image', verbose_name='تصویر')),
                ('project_address', models.CharField(max_length=200, verbose_name='آدرس پروژه')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع پروژه')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ  پایان پروژه')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('skillss_category', models.ManyToManyField(to='projects.Skills_category', verbose_name='دسته بندی پروژه بر اساس مهارت ')),
            ],
            options={
                'verbose_name': 'پروژه ها',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
