version: "3"

services:
  alfax_postgresql:
    image: postgres:12
    container_name: alfax_postgresql
    volumes:
      -  alfax_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - alfax_network

volumes:
  alfax_postgresql:
    external: true
networks:
  alfax_network:
    external: true



