# Generated by Django 3.1.7 on 2021-03-19 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameandfamily', models.CharField(max_length=50)),
                ('companyname', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(default=None, max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='user_avatar')),
                ('address', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=20)),
                ('startregister', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='user_avatar')),
                ('address', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=20)),
                ('startregister', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenumber', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('pub_date', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('invoicenumber', models.IntegerField()),
                ('customername', models.CharField(max_length=30)),
                ('projectname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('pub_date', models.DateTimeField()),
                ('typeofsystem', models.CharField(choices=[('D', 'Direct'), ('I', 'Indirect'), ('T', 'Telescopic')], default='I', max_length=3)),
                ('travel', models.FloatField()),
                ('weighthuman', models.IntegerField(blank=True, default=None, null=True)),
                ('weightcaresling', models.IntegerField(blank=True, default=None, null=True)),
                ('v', models.FloatField(blank=True, default=None, null=True)),
                ('carsling', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('powerunit', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('motortype', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('motorpower', models.FloatField(blank=True, default=None, null=True)),
                ('typeofpomp', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('pomplitr', models.IntegerField(blank=True, default=None, null=True)),
                ('typeofvalve', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('tanklitr', models.IntegerField(blank=True, default=None, null=True)),
                ('oil', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('oirlitr', models.IntegerField(blank=True, default=None, null=True)),
                ('shelang', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('shelangmeter', models.IntegerField(blank=True, default=None, null=True)),
                ('oilheater', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('valverobgard', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('valveks', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('handpomp', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('rapcher', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('oilcolder', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('jack', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('flo', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('packingtype', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('typeofshaft', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('shaftdiameter', models.IntegerField(blank=True, default=None, null=True)),
                ('manisman', models.IntegerField(blank=True, default=None, null=True)),
                ('jacksizeclose', models.FloatField(blank=True, default=None, null=True)),
                ('jackcorse', models.FloatField(blank=True, default=None, null=True)),
                ('Tablobarq', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('price', models.BigIntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('pub_date', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('pub_date', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default=None)),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
